version: '3'
services:
  nginx:
    build: ./nginx
    volumes:
      - ./website:/var/www/html
    ports:
      - '8080:80'
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./website:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
    command:
      - /bin/sh
      - -c
      - |
          docker-php-ext-install mysqli
          php-fpm

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: dbname
      MARIADB_USER: dbuser
      MARIADB_PASSWORD: dbpass
